SELECT 
    AGENDAMENTOS.ID_AGENDAMENTO, 
    AGENDAMENTOS.NOME AS NomeAgendamento, 
    AGENDAMENTOS.DESCRICAO, 
    AGENDAMENTOS.DATA_AGENDAMENTO, 
    AGENDAMENTOS.HORA_INCIAL, 
    AGENDAMENTOS.HORA_FINAL,
    USUARIO.USER_NAME AS NomeUsuario
FROM 
    AGENDAMENTOS
JOIN 
    USUARIO ON AGENDAMENTOS.USUARIO_ID = USUARIO.ID_USER
WHERE 
    USUARIO.USER_NAME = 'Joao'
LIMIT 1;
