CREATE DATABASE AGENDAMENTO; 
USE AGENDAMENTO; 

CREATE TABLE PERFIL(
	ID_PERFIL INT NOT NULL auto_increment, 
    TIPO_PERFIL VARCHAR(16) NOT NULL, 
    PRIMARY KEY(ID_PERFIL)
);

CREATE TABLE USUARIO(
	ID_USER INT NOT NULL auto_increment, 
    USER_NAME VARCHAR(16) NOT NULL, 
    EMAIL VARCHAR(255) NOT NULL, 
    SENHA VARCHAR(8) NOT NULL, 
	CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PERFIL_ID INT,
    PRIMARY KEY(ID_USER), 
    FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL(ID_PERFIL)
);

CREATE TABLE USUARIO_DADOS(
	ID_DADOS INT NOT NULL auto_increment, 
    RUA VARCHAR(16) NOT NULL, 
    CIDADE VARCHAR(255) NOT NULL, 
    CEP VARCHAR(32) NOT NULL, 
    TELEFONE VARCHAR(32) NOT NULL,
    CPF VARCHAR(32) NOT NULL,
    USUARIO_ID INT, 
    PRIMARY KEY(ID_DADOS), 
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USER)
);

CREATE TABLE TIPO_AGENDAMENTO(
	ID_TIPO INT NOT NULL auto_increment, 
    NOME VARCHAR(16) NOT NULL, 
    PRIMARY KEY(ID_TIPO)
);


CREATE TABLE AGENDAMENTOS(
	ID_AGENDAMENTO INT NOT NULL auto_increment, 
    NOME VARCHAR(45) NOT NULL, 
    DESCRICAO VARCHAR(255) NOT NULL, 
    DATA_AGENDAMENTO DATETIME, 
	HORA_INCIAL TIME NOT NULL,
    HORA_FINAL TIME NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    USUARIO_ID INT, 
    TIPO_ID INT, 
    PRIMARY KEY(ID_AGENDAMENTO), 
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USER), 
    FOREIGN KEY (TIPO_ID) REFERENCES TIPO_AGENDAMENTO(ID_TIPO)
);
